# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4ce7c327-458a-4e09-a316-995bce9087b9";
      fsType = "ext4";
    };

  nix.maxJobs = 2;
  nix.buildCores = lib.mkDefault 4;
}
