# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/13a898d6-de9b-48bc-8713-6c720664ceab";
    fsType = "ext4";
  };

  swapDevices = lib.singleton {
    device = "/swap";
    size = 1024;
  };

  nix.settings.cores = 4;
}
