# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/35003c68-484a-4f31-8ec6-c44c987b0ae3";
    fsType = "ext4";
  };

  swapDevices = lib.singleton {
    device = "/swap";
    size = 1024;
  };

  nix.settings.cores = 4;
}
