name: "Update nixpkgs"
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
jobs:
  update-nixpkgs:
    name: Update nixpkgs (${{ matrix.branch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: master-custom
            upstream-branch: master
          - branch: unstable-custom
            upstream-branch: nixos-unstable
    steps:
      # Supports filter option
      # https://github.com/actions/checkout/pull/1396
      - uses: finleygn/checkout@573932dbdda76b2055415af22b663867dae9bdc3
        with:
          repository: lopsided98/nixpkgs
          ref: ${{ matrix.branch }}
          filter: tree:0
          fetch-depth: 0
          token: ${{ secrets.NIXPKGS_GITHUB_TOKEN }}
      - name: Update nixpkgs
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git remote add upstream https://github.com/NixOS/nixpkgs.git
          git fetch --filter=tree:0 upstream ${{ matrix.upstream-branch }}
          git rebase upstream/${{ matrix.upstream-branch }}
          git push --force-with-lease
  update-flake:
    name: Update nixpkgs inputs in flake
    runs-on: ubuntu-latest
    needs: update-nixpkgs
    permissions:
      contents: write
    steps:
      # Supports filter option
      # https://github.com/actions/checkout/pull/1396
      - uses: finleygn/checkout@573932dbdda76b2055415af22b663867dae9bdc3
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update flake inputs
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          nix flake lock \
            --update-input nixpkgs-master-custom \
            --update-input nixpkgs-unstable-custom \
            --commit-lock-file
          git push
